### ISSUE TITLE
Chrome error: localhost refused to connect.

### ISSUE THREAD

**Issue by revikiran1991** [Wesleyliao/QWOP-RL#1]
Dear  Wesley Liao
I recently came across your video and implementation. I wanted to try training your network, but I came across this error.

```Traceback (most recent call last):
  File "main.py", line 220, in <module>
    main()
  File "/home/ravi/anaconda3/envs/py3.7_tf1.14.0/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ravi/anaconda3/envs/py3.7_tf1.14.0/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ravi/anaconda3/envs/py3.7_tf1.14.0/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ravi/anaconda3/envs/py3.7_tf1.14.0/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 200, in main
    run_train()
  File "main.py", line 95, in run_train
    model = get_model(model_path)
  File "main.py", line 86, in get_model
    model = get_existing_model(model_path)
  File "main.py", line 77, in get_existing_model
    env = QWOPEnv()  # SubprocVecEnv([lambda: QWOPEnv()])
  File "/home/ravi/thesis_2/test_repos/QWOP-RL/game/env.py", line 55, in __init__
    self.driver.get(f'http://localhost:{PORT}/Athletics.html')
  File "/home/ravi/anaconda3/envs/py3.7_tf1.14.0/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ravi/anaconda3/envs/py3.7_tf1.14.0/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ravi/anaconda3/envs/py3.7_tf1.14.0/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=89.0.4389.90)```

Can you please help me in solving this?

**Comment by Wesleyliao** [comment]
Hm I haven't seen that error before. Did you download the right version of Chromedriver (for your version of Chrome) from https://chromedriver.chromium.org/, and put it in a PATH directory?

**Comment by Wesleyliao** [comment]
Did you host the game separately with `python host_game.py`?

**Comment by revikiran1991** [comment]
Thank you for your kind reply. I am a newbee to coding.

I did host the game and installed the right chromedriver. Now I am getting the error from geckodriver. 

```selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.```

I am figuring it out now.

**Comment by revikiran1991** [comment]
Thank you. I solved it. Nice to get a reply from you.
